### PR TITLE
Make table headers clickable for sorting.

### PR DESCRIPTION
**Pull request by s-ludwig**
Also adds a new "Added" column to make this scheme work. This looks a little bulky currently, any ideas for making that prettier (without too much work)?
header-sort

### CODE REVIEW

**Comment by PxlBuzzard** [comment]
On the topic of dates, it would be great to do some localization / beautification. With a library like [time-elements](https://github.com/github/time-elements) you can let the client choose how to format a date. Dub could use a relative time for the *Updated* column and a local time for *Added*.

**Comment by s-ludwig** [comment]
Oh right, good idea, I always wanted to add relative dates, but completely forgot about them. Maybe the "Current version" and "Updated" columns could also be merged in that process:
<table>
<tr>
<th>Name</th>
<th>Last update</th>
<th>Registered</th>
<th>Description</th>
</tr>
<td>onyx-log</td>
<td>1.0.0-beta.2<em>, updated 2 hours ago</em></td>
<td>2015/04/16</td>
<td>Log library for D</td>
</tr>
</table>

Regarding localized dates, that may look a little out of place as long as the rest of the site isn't localized. Not sure if that makes sense at all, because virtually all content will be in English anyway.

**Comment by s-ludwig** [comment]
Now looks like this:
header-sort2

**Comment by PxlBuzzard** [comment]
:+1: I think that looks good and I like the minimal implementation in D.

**Comment by s-ludwig** [comment]
Okay, I also think that's a decent solution. I'll merge and deploy.

**Pull request merged**
